version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  indexer:
    build: .
    command: python -m pipelines.indexing.service
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
      - api

volumes:
  mongo_data:
  redis_data: